spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:config/core/{application}
            - classpath:config/infra/{application}
            - classpath:config/stats/{application}

server:
  port: 0