server:
  port: 9999

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:./db/user-db
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        show_sql: true
  sql:
    init:
      mode: always
