spring:
  sql:
    init:
      mode: always

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://like-db:5432/ewm-like
    username: root
    password: root

server:
  port: 0