DROP TABLE IF EXISTS LIKES_EVENTS CASCADE;
DROP TABLE IF EXISTS LIKES_LOCATIONS CASCADE;

CREATE TABLE IF NOT EXISTS LIKES_EVENTS
(
    EVENT_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    CONSTRAINT LIKES_EVENTS_PK
        PRIMARY KEY (EVENT_ID, USER_ID)
);

CREATE TABLE IF NOT EXISTS LIKES_LOCATIONS
(
    LOCATION_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    CONSTRAINT LIKES_PK
        PRIMARY KEY (LOCATION_ID, USER_ID)
);